#:import Factory kivy.factory.Factory
#This is not a comment, do not delete it!
WindowManager:
  MainWindow2:
  InsideWindow:
  ChangeWindow:
  ForgotWindow:

<tabs>:
  name: "main"
  size_hint: 1,1
  do_default_tab: False
  tab_pos: "top_mid"

  usernameLogin: usernameLogin
  password : password
  username : username
  passwordSignUp : passwordSignUp
  email: email

  TabbedPanelItem:
    text: 'SignUp'

    FloatLayout:
      canvas.before:
        Color:
          rgba: 1, 1, 1, 1
        Rectangle:
          pos: self.pos
          size: self.size

      Label:
        text: "SignUp" 
        size_hint: 1,0.2
        pos_hint: {"top":0.95}
        font_size:'80sp'
        background_color: (0,0,0,0)
        canvas.before:
          Color:
            rgba: self.background_color
          Rectangle:
            size: self.size
            pos: self.pos
        color: (1,0,0,1)
        bold: True
        outline_color: (0,0,0,0)
        outline_width: 2

      FloatLayout: #This creates the border around the stuff
        size_hint: 0.8,0.8 # Decreases the size dynamically
        pos_hint: {"center_x" : 0.5, "center_y" : 0.35} # Centers the stuff

        FloatLayout:
          size_hint: 0.8, 0.4
          pos_hint: {"top" : 0.9, "right" : 0.9}


          TextInput:
            size_hint: 1, 0.3
            pos_hint: {"top" : 1.1, "right" : 1}
            id: username
            multiline: False
            text: "Enter username here:"
            on_touch_down: if self.collide_point(*args[1].pos) and self.text == 'Enter username here:': self.text = ""
            on_touch_up: if self.text == "": self.text = "Enter username here:"
            font_size: (root.width**2 + root.height**2) / 13.3**4
            background_color: (0.9,0.9,0.9,0.5)
            foreground_color: (0.3, 0.3, 0.3, 0.5) if self.text == "Enter username here:" else (0.3, 0.3, 0.3, 1)

          TextInput:
            size_hint: 1, 0.3
            pos_hint: {"top" : 0.7, "right" : 1}
            id: passwordSignUp
            multiline: False
            text: "Enter password here:"
            on_touch_down: if self.collide_point(*args[1].pos) and self.text == "Enter password here:": self.text = ""
            on_touch_up: if self.text == "": self.text = "Enter password here:"
            font_size: (root.width**2 + root.height**2) / 13.3**4
            background_color: (0.9,0.9,0.9,0.5)
            foreground_color: (0.3, 0.3, 0.3, 0.5) if self.text == "Enter password here:" else (0.3, 0.3, 0.3, 1)

          TextInput:
            size_hint: 1, 0.3
            pos_hint: {"top" : 0.3, "right" : 1}
            id: email
            multiline: False
            text: "Enter email here:"
            on_touch_down: if self.collide_point(*args[1].pos) and self.text == 'Enter email here:': self.text = ""
            on_touch_up: if self.text == "": self.text = "Enter email here:"
            font_size: (root.width**2 + root.height**2) / 13.3**4
            background_color: (0.9,0.9,0.9,0.5)
            foreground_color: (0.3, 0.3, 0.3, 0.5) if self.text == "Enter email here:" else (0.3, 0.3, 0.3, 1)

          RoughButton:
            size_hint: 0.8,0.4
            pos_hint: {"top": -0.2, "x": 0.1}
            text: "Create Account"
            on_release:
              app.root._username = username.text
              app.root._password = passwordSignUp.text
              if root.get_create_account_info() == "success": passwordSignUp.text = "Enter password here:"; username.text = "Enter username here:"; email.text = "Enter email here:";  app.root.current = "inside"
              #Factory.SRP().open();
              app.root.backend_login(app.root._username, app.root._password)
              #else
            font_size: (root.width**2 + root.height**2) / 12**4 


  TabbedPanelItem:
    text: 'Login'
    
    FloatLayout:
      pos_hint: {"top": 1.2}
      canvas.before:
        Color:
          rgba: 1, 1, 1, 1
        Rectangle:
          pos: self.pos
          size: self.size

      Label:
        text: "Login" 
        size_hint: 1,0.2
        pos_hint: {"top":0.9, "right" : 1 }
        font_size:'100sp'
        background_color: (0,0,0,0)
        canvas.before:
          Color:
            rgba: self.background_color
          Rectangle:
            size: self.size
            pos: self.pos
        color: (1,0,0,1)
        bold: True
        outline_color: (0,0,0)
        outline_width: 2

      FloatLayout:
        size_hint: 0.8,0.8 # Decreases the size dynamically
        pos_hint: {"top" : 0.6, "right" : 0.9} # Centers the stuff
        
        FloatLayout:
          size_hint: 0.8, 0.6
          pos_hint: {"top" : 1.05, "right" : 0.9}

          TextInput:
            size_hint: 1, 0.25
            pos_hint: {"top" : 0.95, "right" : 1}
            id: usernameLogin
            multiline: False
            font_size: (root.width**2 + root.height**2) / 12.5**4
            text: "Enter username here:"
            on_touch_down: if self.collide_point(*args[1].pos) and self.text == 'Enter username here:': self.text = ""
            on_touch_up: if self.text == "": self.text = "Enter username here:"
            background_color: (0.9,0.9,0.9,0.5)
            foreground_color: (0.3, 0.3, 0.3, 0.5) if self.text == "Enter username here:" else (0.3, 0.3, 0.3, 1)

          TextInput:
            size_hint: 1, 0.25
            pos_hint: {"top" : 0.55, "right" : 1}
            id: password
            multiline: False
            font_size: (root.width**2 + root.height**2) / 12.5**4
            text: "Enter password here: " 

            on_touch_down: if self.collide_point(*args[1].pos) and self.text == "Enter password here: ": self.text = ""
            on_touch_up: if self.text == "": self.text = "Enter password here: "
            background_color: (0.9,0.9,0.9,0.5)
            foreground_color: (0.3, 0.3, 0.3, 0.5) if self.text == "Enter password here: " else (0.3, 0.3, 0.3, 1)
            
          Button:
            text: "Forgot your password?"
            font_size: (root.width**2 + root.height**2) / 14.5**4
            size_hint: 1,0.2
            pos_hint: {"top":0.3, "center_x" : 0.22}
            background_color: (0,0,0,0)
            canvas.before:
              Color:
                rgba: self.background_color
              Rectangle:
                size: self.size
                pos: self.pos
            color: (0.2,0.2,1,0.8)
            on_release:
              app.root.current = "Forgot"

          SmoothButton:
            size_hint: 0.8,0.25
            pos_hint: {"top" : 0.08, "center_x" : 0.5}
            text: "Login"
            font_size: (root.width**2 + root.height**2) / 12**4
            #canvas.before:
              #Color:
                #rgba: 0.1, 0.6, 0.1, 1 if on_state == "down" else 0.1,0.8,0.1,1
            on_release:
              root.get_login_info()
              usernameLogin.text = "Enter username here:"
              password.text = "Enter password here: "

<MainWindow2>:
  name: "main"
  Label:
  tabs:

<InsideWindow>:
  name: "inside"

  FloatLayout:
    canvas.before:
      Color:
        rgba: 1, 1, 1, 1
      Rectangle:
        pos: self.pos
        size: self.size

  FloatLayout:
  
    Label:
      pos_hint: {"top": 0.9}
      size_hint: 1,0.2
      font_size: '80'
      text: "Successfully\n  Logged in"
      background_color: (0,0,0,0)
      canvas.before:
        Color:
          rgba: self.background_color
        Rectangle:
          size: self.size
          pos: self.pos
      color: (1,0,0,1)
      bold: True
      outline_color: (0,0,0)
      outline_width: 3

    CoolButton:
      text: "Log Out"
      font_size: '40'
      size_hint: 0.4,0.15
      pos_hint: {"top" : 0.3, "right" : 0.7}
      on_release:
        root.logout()
        root.manager.transition.direction = "down"
        app.root.current = "main"

    CoolButton:
      text: "Change password"
      font_size: '28'
      size_hint: 0.4,0.15
      pos_hint: {"top" : 0.5, "right" : 0.7}
      on_release:
        root.manager.transition.direction = "down"
        app.root.current = "change"
     
<ChangeWindow>:
  name: "change"

  new_password : new_password
  new_password_confirm : new_password_confirm

  FloatLayout:
    canvas.before:
      Color:
        rgba: 1, 1, 1, 1
      Rectangle:
        pos: self.pos
        size: self.size
  
  FloatLayout:
    Label:
      text: "Change Password" 
      size_hint: 1,0.2
      pos_hint: {"top":0.9, "right" : 1 }
      font_size:(root.width**2 + root.height**2) / 10.2**4
      background_color: (0,0,0,0)
      canvas.before:
        Color:
          rgba: self.background_color
        Rectangle:
          size: self.size
          pos: self.pos
      color: (1,0,0,1)
      bold: True
      outline_color: (0,0,0)
      outline_width: 2

    TextInput:
      size_hint: 0.9, 0.125
      pos_hint: {"top" : 0.6, "center_x" : 0.5}
      id: new_password
      multiline: False
      font_size: (root.width**2 + root.height**2) / 12**4
      text: "Enter new password here: " 

      on_touch_down: if self.collide_point(*args[1].pos) and self.text == "Enter new password here: ": self.text = ""
      on_touch_up: if self.text == "": self.text = "Enter new password here: "
      background_color: (0.9,0.9,0.9,0.5)
      foreground_color: (0.3, 0.3, 0.3, 0.5) if self.text == "Enter new password here: " else (0.3, 0.3, 0.3, 1)

    TextInput:
      size_hint: 0.9, 0.125
      pos_hint: {"top" : 0.4, "center_x" : 0.5}
      id: new_password_confirm
      multiline: False
      font_size: (root.width**2 + root.height**2) / 12**4
      text: "Confirm new password here: " 

      on_touch_down: if self.collide_point(*args[1].pos) and self.text == "Confirm new password here: ": self.text = ""
      on_touch_up: if self.text == "": self.text = "Confirm new password here: "
      background_color: (0.9,0.9,0.9,0.5)
      foreground_color: (0.3, 0.3, 0.3, 0.5) if self.text == "Confirm new password here: " else (0.3, 0.3, 0.3, 1)

    Button:
      text: "Change password"
      font_size: '28'
      size_hint: 0.4,0.15
      pos_hint: {"top" : 0.2, "center_x" : 0.5}
      background_normal: ""
      background_color: (0.1,0.8,0.1,1)
      on_release:
        if root.change_password(new_password.text, new_password_confirm.text): root.manager.transition.direction = "down";app.root.current = "inside"; new_password.text = ""; new_password_confirm.text = ""

<SmoothButton@Button>:
  border_radius: [50]
  background_normal: ""
  background_color: (0.1,0.8,0.1,0)
  canvas.before:
    Color:
      rgba: 0.1, 0.8, 0.1, 1
    RoundedRectangle:
      size: self.size
      pos: self.pos
      radius: self.border_radius

<RoughButton@Button>:
  border_radius: [50]
  background_normal: ""
  background_color: (0.1,0.8,0.1,0)
  canvas.before:
    Color:
      rgba: 0.1, 0.8, 0.1, 1
    RoundedRectangle:
      size: self.size
      pos: self.pos
      radius: self.border_radius

<CoolButton@Button>:
  border_radius: [100]
  background_normal: ""
  background_color: (0.1,0.8,0.1,0)
  canvas.before:
    Color:
      rgba: 0.1, 0.8, 0.1, 1
    RoundedRectangle:
      size: self.size
      pos: self.pos
      #radius: self.border_radius

<SRP@Popup>: #Successful registration popup
  title: "Successful Account Registration"
  size_hint: (0.4,0.6)

  FloatLayout:
    size_hint: (0.4,0.6)
    pos_hint: {"center_x": 0.5, "center_y": 0.5}

    Button:
      size_hint: 1,0.4
      pos_hint: {"center_x": 0.5, "center_y": 0.2}
      text:"Login Here:"
      on_release:
        # need help here, thx        
        #Is this good? Check main.py backend_login()method under Window Manager
        app.root.current = "inside"
        app.root.backend_login(app.root._username, app.root._password)
        root.dismiss()

<SendEmailButton@Button>:
  border_radius: [50]
  background_normal: ""
  background_color: (0.1,0.8,0.1,0)
  canvas.before:
    Color:
      rgba: 0.1, 0.8, 0.1, 1
    RoundedRectangle:
      size: self.size
      pos: self.pos
      radius: self.border_radius

<ForgotWindow>:
  name: "Forgot"

  FloatLayout:
    canvas.before:
      Color:
        rgba: 1, 1, 1, 1
      Rectangle:
        pos: self.pos
        size: self.size

    Label:
      text: "Forgot Password" 
      size_hint: 1,0.2
      pos_hint: {"top":0.95}
      font_size: (root.width**2 + root.height**2) / 11**4
      background_color: (0,0,0,0)
      canvas.before:
        Color:
          rgba: self.background_color
        Rectangle:
          size: self.size
          pos: self.pos
      color: (1,0,0,1)
      bold: True
      outline_color: (0,0,0,0)
      outline_width: 2

    TextInput:
      size_hint: 0.8, 0.1
      pos_hint: {"center_y" : 0.6, "center_x" : 0.5}
      id: email
      multiline: False
      text: "Enter email here:"
      on_touch_down: if self.collide_point(*args[1].pos) and self.text == 'Enter email here:': self.text = ""
      on_touch_up: if self.text == "": self.text = "Enter email here:"
      font_size: (root.width**2 + root.height**2) / 13.3**4
      background_color: (0.9,0.9,0.9,0.5)
      foreground_color: (0.3, 0.3, 0.3, 0.5) if self.text == "Enter email here:" else (0.3, 0.3, 0.3, 1)
      
    Button:
      size_hint: 0.8,0.15
      pos_hint: {"center_y" : 0.3, "center_x" : 0.5}
      text: "Send Email"
      font_size: (root.width**2 + root.height**2) / 12**4
      border_radius: [50]
      background_normal: ""
      background_color: (0.1,0.8,0.1,0)
      canvas.before:
        Color:
          rgba: 0.1, 0.8, 0.1, 1
        RoundedRectangle:
          size: self.size
          pos: self.pos
          radius: self.border_radius
      on_release:
        root.forgot_password(email.text)
        #app.root.current = "main"
    